#!/usr/bin/env python3
"""Render every voice in ``tools/voices/`` into ``sounds/``.

Each voice module exposes:

    NAME        short id, must match the file name          e.g. "microwave"
    TITLE       one-line human label                        e.g. "Microwave"
    DESCRIPTION one sentence shown by ``/dziling``
    render()    -> list of floats in [-1, 1] at dsp.SR

``render()`` returns raw material at whatever level is convenient; the output
stage is ``dsp.master`` (trim, fade, peak-normalise, match loudness), which
``render_one.py`` shares so a preview and a release are the same bytes.  That
loudness match is why the shipped files do not all peak at 0.89: they are
matched to each other's level instead, so switching sounds does not change how
loud dziling is.

Run ``python3 tools/generate_sounds.py`` after touching a voice; the WAVs are
committed so the plugin works without a build step.
"""

import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VOICES = os.path.join(HERE, "voices")
OUT = os.path.join(ROOT, "sounds")

sys.path.insert(0, HERE)
import dsp  # noqa: E402


def load(path):
    name = os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location("voice_" + name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    for attr in ("NAME", "TITLE", "DESCRIPTION", "render"):
        if not hasattr(mod, attr):
            raise SystemExit("%s: voice module is missing %s" % (path, attr))
    if mod.NAME != name:
        raise SystemExit("%s: NAME is %r but the file is %r" % (path, mod.NAME, name))
    return mod


def main(argv):
    only = set(argv[1:])
    os.makedirs(OUT, exist_ok=True)
    paths = sorted(
        os.path.join(VOICES, f)
        for f in os.listdir(VOICES)
        if f.endswith(".py") and not f.startswith("_")
    )
    rows = []
    for path in paths:
        mod = load(path)
        if only and mod.NAME not in only:
            # Keep the manifest complete even when re-rendering a single voice.
            rows.append((mod.NAME, mod.TITLE, mod.DESCRIPTION))
            continue
        sig = dsp.master(mod.render())
        wav = os.path.join(OUT, mod.NAME + ".wav")
        secs = dsp.write_wav(wav, sig)
        rows.append((mod.NAME, mod.TITLE, mod.DESCRIPTION))
        print(
            "%-12s %5.2fs %6.1f KiB  peak %.3f  %6.2f LUFS  %s"
            % (mod.NAME, secs, os.path.getsize(wav) / 1024.0,
               max(abs(v) for v in sig), dsp.loudness(sig), mod.TITLE)
        )

    with open(os.path.join(OUT, "sounds.tsv"), "w") as fh:
        fh.write("# name\ttitle\tdescription -- generated by tools/generate_sounds.py\n")
        for row in sorted(rows):
            fh.write("\t".join(row) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
